#!/usr/bin/env python3
from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

from context_db import load_config
from custom_checks import run_custom_checks


def _run(py: Path, args: list[str]) -> int:
    cmd = [sys.executable, str(py), *args]
    p = subprocess.run(cmd)
    return p.returncode


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description="vibe-kit doctor: full scan + reports.")
    parser.add_argument("--full", action="store_true", help="Force full rescan + full context refresh.")
    parser.add_argument("--profile", action="store_true", help="Summarize perf logs if present (no injection).")
    args = parser.parse_args(argv)

    cfg = load_config()
    brain = cfg.root / ".vibe" / "brain"

    # Full scan to refresh DB.
    if args.full:
        rc = _run(brain / "indexer.py", ["--scan-all"])
        if rc:
            return rc
    else:
        # Light mode: still attempt a scan-all (fast if hashes unchanged)
        _run(brain / "indexer.py", ["--scan-all"])

    failures: list[tuple[str, int]] = []

    def step(name: str, script: str, args_: list[str] | None = None) -> None:
        rc2 = _run(brain / script, args_ or [])
        if rc2 != 0:
            failures.append((name, rc2))

    step("hotspots", "dependency_hotspots.py")
    step("complexity", "check_complexity.py")
    step("typecheck", "typecheck_baseline.py")
    step("cycles", "check_circular.py")
    step("boundaries", "check_boundaries.py")
    if args.full:
        step("coupling", "change_coupling.py", ["--best-effort"])

    if args.profile:
        step("profile", "perf_profiler.py", ["--summarize-only"])

    custom_failures: list[tuple[str, int]] = []
    checks_cfg = cfg.checks or {}
    doctor_checks = checks_cfg.get("doctor")
    if isinstance(doctor_checks, list) and doctor_checks:
        report_path = cfg.root / ".vibe" / "reports" / "custom_checks.json"
        _, custom_failures = run_custom_checks(cfg, doctor_checks, report_path=report_path)

    _run(brain / "summarizer.py", ["--full"] if args.full else [])

    report = cfg.root / ".vibe" / "reports" / "doctor_report.md"
    report.parent.mkdir(parents=True, exist_ok=True)
    report_lines = [
        "# doctor_report",
        "",
        "Generated by vibe-kit.",
        "",
        "- See `.vibe/context/LATEST_CONTEXT.md`",
        "- See `.vibe/reports/hotspots.json`, `.vibe/reports/complexity.json`, `.vibe/reports/typecheck_status.json`",
        "- See `.vibe/reports/boundaries.json` (optional, config-driven)",
        "- See `.vibe/reports/custom_checks.json` (optional, config-driven)",
        "",
    ]
    failures.extend(custom_failures)
    if failures:
        report_lines.append("## Failures")
        for name, rc2 in failures:
            report_lines.append(f"- {name}: exit {rc2}")
        report_lines.append("")
    report.write_text("\n".join(report_lines), encoding="utf-8")
    print(f"[doctor] wrote: {report}")
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main(__import__("sys").argv[1:]))
